"""add style fields to channels

Revision ID: 01cddc07990b
Revises: a1b2c3d4e5f6
Create Date: 2026-03-15 05:33:41.593246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01cddc07990b'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('image_style_prompt', sa.Text(), nullable=True))
    op.add_column('channels', sa.Column('negative_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'negative_prompt')
    op.drop_column('channels', 'image_style_prompt')
    # ### end Alembic commands ###
