"""add_video_resolution

Revision ID: 1bcdcaf9268a
Revises: d461edc64851
Create Date: 2026-03-06 17:00:45.336437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bcdcaf9268a'
down_revision: Union[str, None] = 'd461edc64851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'height')
    op.drop_column('videos', 'width')
    # ### end Alembic commands ###
