"""add last_error to video

Revision ID: 1d361253c65e
Revises: 1bcdcaf9268a
Create Date: 2026-03-07 05:29:09.816322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d361253c65e'
down_revision: Union[str, None] = '1bcdcaf9268a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('last_error', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'last_error')
    # ### end Alembic commands ###
