"""Add UserSettings

Revision ID: 7a9c19a4c228
Revises: 2bce5db9ffd9
Create Date: 2026-04-03 07:38:29.824590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9c19a4c228'
down_revision: Union[str, None] = '2bce5db9ffd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
