"""add_youtube_seo_fields

Revision ID: 85522d7b89ab
Revises: 8577a3b057e4
Create Date: 2026-03-07 11:45:23.073461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85522d7b89ab'
down_revision: Union[str, None] = '8577a3b057e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('youtube_title', sa.String(length=100), nullable=True))
    op.add_column('videos', sa.Column('youtube_description', sa.Text(), nullable=True))
    op.add_column('videos', sa.Column('youtube_tags', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'youtube_tags')
    op.drop_column('videos', 'youtube_description')
    op.drop_column('videos', 'youtube_title')
    # ### end Alembic commands ###
